apiVersion: v1
kind: Service
metadata:
  name: validator-api
  labels:
    app: validator-api
spec:
  selector:
    app: validator-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer